### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by theofidry** [lanthaler/HydraConsole#19]
Hi @lanthaler. Do you have any kind of roadmap for this tool? Is see some recent issues but no commit. Is this project still active?

**Comment by lanthaler** [comment]
Hi Théo, no I don't really have a roadmap apart from fully supporting the [Hydra Core Vocabulary](http://www.hydra-cg.com/spec/latest/core/). Another thing I really wanted to do is to refactor and componetize it.
It is still active but I have very little time to work on it at the moment. Help is greatly welcome ;-P

**Comment by theofidry** [comment]
Neither do I but it's definitely a project I'll keep in check and contribute to when I can :) I'm sort of interested to port it into a bundle for coupling it with [DunglasApiBundle](https://github.com/dunglas/DunglasApiBundle) first but I'm sure this will lead to some new feature requests and new things.

**Comment by lanthaler** [comment]
Btw. if you are interested in Hydra you should consider joining the [Hydra W3C Community Group](https://www.w3.org/community/hydra/). For details, see here: http://www.hydra-cg.com/#community

**Comment by theofidry** [comment]
Thanks for the link :)
