### ISSUE TITLE
Error with PHP 7.2

### ISSUE THREAD

**Issue by dunglas** [lanthaler/HydraConsole#28]
Hello,

There is a bug when using HydraConsole with PHP 7.2:

> Fatal error: Cannot use stdClass as Object because 'Object' is a special class name in /Users/dunglas/workspace/hydra-console/vendor/ml/json-ld/ML/JsonLD/JsonLD.php on line 12

It looks related to the new `object` return type introduced in this version.

**Comment by BonnieDoug** [comment]
I can confirm this error is also present for me.

> [Tue Mar 27 10:23:06 2018] PHP Fatal error:  Cannot use stdClass as Object because 'Object' is a special class name in /hydra-test/vendor/ml/json-ld/ML/JsonLD/JsonLD.php on line 12
> [Tue Mar 27 10:23:06 2018] ::1:33402 [500]: /proxy.php?debug=true&url={url-here} - Cannot use stdClass as Object because 'Object' is a special class name in /hydra-test/vendor/ml/json-ld/ML/JsonLD/JsonLD.php on line 12

```
PHP 7.2.2 (cli) (built: Jan 30 2018 10:33:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies  with Zend OPcache v7.2.2, Copyright (c) 1999-2018, by Zend Technologies

```

**Comment by gustavodemorais** [comment]
Probably not the best place to comment on this but I think the online version here http://www.markus-lanthaler.com/hydra/console/ is not working for the same reason.

![image](https://user-images.githubusercontent.com/11739405/54696631-7419c180-4b2c-11e9-89c3-e497a0cf605e.png)

**Comment by lanthaler** [comment]
Thanks for the bug report. The issue has been fixed and the Hydra console on my page has been updated and works again.

**Comment by gustavodemorais** [comment]
Thanks for fixing it fast, it's a nice tool for the community
